### ISSUE TITLE
Yapılacak düzenlemeler ve eklemeler

### ISSUE THREAD

**Issue by OkanUzun** [denizguzel/hastane-randevu#6]
Admin girişi ayrı bir yerden olsun (ayrı bir link), doktorun ve kullanıcının girdiği yerden olmasın.
Sistemde hiç aktif randevum olmamasına rağmen google map çıkıyor, eğer closestAppointment yoksa gösterilmesin.
Ana sayfada ve randevularım sayfasındaki mesaj aynı, değiştirilmesi gerekiyor. Ana sayfada gösterilen randevular kullanıcının sadece geçmiş olan randevuları, randevularım sayfasındaki randevular geçmiş randevularla birlikte aktif randevuların gösterildiği bir yer.
Poliklinik seçerken textbox içinden arama yapabilmeliyim (şehir ve ilçede olduğu gibi..)

--------------------------------

Admin kısmında olması gerekenler
-Anket oluşturma, anketi yayından kaldırma, anket istatistiklerini görebilme.
-Doktor için yapılan değerlendirilmelerin onaylanması ve onaylanmaması
-En fazla randevu alan poliklinikler istatiksel bilgi olarak gösterilebilir.
-Sistemde kayıtlı kullanıcı sayısı (kullanıcıları göstermeye gerek yok sayı olarak göstersek yeter)

**Comment by denizguzel** [comment]
Son durum güncellemesi,
> Admin girişi ayrı bir yerden olsun (ayrı bir link), doktorun ve kullanıcının girdiği yerden olmasın.
Sistemde hiç aktif randevum olmamasına rağmen google map çıkıyor, eğer closestAppointment yoksa gösterilmesin.
Ana sayfada ve randevularım sayfasındaki mesaj aynı, değiştirilmesi gerekiyor. Ana sayfada gösterilen randevular kullanıcının sadece geçmiş olan randevuları, randevularım sayfasındaki randevular geçmiş randevularla birlikte aktif randevuların gösterildiği bir yer.
Poliklinik seçerken textbox içinden arama yapabilmeliyim (şehir ve ilçede olduğu gibi..)

> Admin kısmında olması gerekenler
-Anket oluşturma, anketi yayından kaldırma, anket istatistiklerini görebilme.
-Doktor için yapılan değerlendirilmelerin onaylanması ve onaylanmaması
-Sistemde kayıtlı kullanıcı sayısı (kullanıcıları göstermeye gerek yok sayı olarak göstersek yeter)

Üsttekiler tamamlandı. Tamamlanmayanlar aşağıda

> -En fazla randevu alan poliklinikler istatiksel bilgi olarak gösterilebilir.
